In [1]:
# two type of array in python array- array , array in numpy (much more veratile and control)

In [72]:
import numpy as np

In [7]:
l = [22345,6,789,109] # it is a list

In [8]:
a = np.array(l)

In [9]:
a

array([22345,     6,   789,   109])

In [6]:
type(a)

numpy.ndarray

In [10]:
# array can't have different datatype in it

In [12]:
b = [543, 234, "test", 12.5]

In [13]:
b1 = np.array(b)

In [14]:
b1

array(['543', '234', 'test', '12.5'], 
      dtype='<U21')

In [15]:
type(b1)

numpy.ndarray

In [16]:
print(b1)

['543' '234' 'test' '12.5']


In [17]:
#Although list canhave different types compare to array but array has way more methods or functions


In [18]:
a.mean() # a. tab allow you to different functions

5812.25

In [19]:
a.max()

22345

In [23]:
c = [123,234,True]

In [24]:
c1 = np.array(c)

In [25]:
print(c1)

[123 234   1]


In [26]:
type(c1)

numpy.ndarray

In [27]:
d = [ 123, 234, "abc"]

In [28]:
d2 = np.array(d)

In [29]:
print(d2)

['123' '234' 'abc']


----

#   SLICING in ARRAY ##

In [31]:
a[1:] # whenever you are slicing array you are not creating a copy , it is actually created a view

array([  6, 789, 109])

In [58]:
a11 =  [1,2,3,4,5,6,7]

In [59]:
a21 = np.array(a11)

In [64]:
b21 = a21[1:4]

In [65]:
b21

array([2, 3, 4])

In [66]:
type(b21)

numpy.ndarray

In [67]:
b21[:]

array([2, 3, 4])

In [68]:
b21[:] = 110

In [69]:
a21

array([  1, 110, 110, 110,   5,   6,   7])

In [71]:
# so you can clearly see in the case of array b21 was view of a21 and momenet we changed elemets values of array b21
# values of a21 got changed too but this will not happen in case of list.