In [1]:
#
#Welcome to the world of Basketball Data!
#I'm sure you will enjoy this section of the Python Programming course.
#
#Instructions for this dataset:
# Simply copy ALL the lines in this script by pressing 
# CTRL+A on Windows or CMND+A on Mac and run the Jupyter cell
# Once you have executed the commands the following objects
# will be created:
# Matrices:
# - Salary
# - Games
# - MinutesPlayed
# - FieldGoals
# - FieldGoalAttempts
# - Points
# Lists:
# - Players
# - Seasons
# Dictionaries:
# - Sdict
# - Pdict
#We will understand these inside the course.
#


#Comments:
#Seasons are labeled based on the first year in the season
#E.g. the 2012-2013 season is preseneted as simply 2012

#Notes and Corrections to the data:
#Kevin Durant: 2006 - College Data Used
#Kevin Durant: 2005 - Proxied With 2006 Data
#Derrick Rose: 2012 - Did Not Play
#Derrick Rose: 2007 - College Data Used
#Derrick Rose: 2006 - Proxied With 2007 Data
#Derrick Rose: 2005 - Proxied With 2007 Data

#Import numpy
import numpy as np

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Salaries
KobeBryant_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])

#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

#Minutes Played
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP, CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP, DerrickRose_MP, DwayneWade_MP])

#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

#Field Goal Attempts
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA, CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA, DerrickRose_FGA, DwayneWade_FGA])

#Points
KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]
#Matrix
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS, DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS, DwayneWade_PTS])             
                  


In [2]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [3]:
Points

array([[2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782],
       [1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154],
       [2478, 2132, 2250, 2304, 2258, 2111, 1683, 2036, 2089, 1743],
       [2122, 1881, 1978, 1504, 1943, 1970, 1245, 1920, 2112,  966],
       [1292, 1443, 1695, 1624, 1503, 1784, 1113, 1296, 1297,  646],
       [1572, 1561, 1496, 1746, 1678, 1438, 1025, 1232, 1281,  928],
       [1258, 1104, 1684, 1781,  841, 1268, 1189, 1186, 1185, 1564],
       [ 903,  903, 1624, 1871, 2472, 2161, 1850, 2280, 2593,  686],
       [ 597,  597,  597, 1361, 1619, 2026,  852,    0,  159,  904],
       [2040, 1397, 1254, 2386, 2045, 1941, 1082, 1463, 1028, 1331]])

In [11]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
matr1 = np.reshape(mydata, (5,4), order = "c") # in R language by default first "Columns" are filled where as in 
# python default filling is row-wise.

In [18]:
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
matr1[2,2]

10

In [29]:
matr2 = np.reshape(mydata,(5,4), order = "F")
matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [30]:
matr2[2,2]

12

In [31]:
#OOP CONCEPT OBJECTS
# np.reshape(mydata,(5,4))
mydata.reshape((5,4))  #mydata , press Tab - "reshape function" in the list of functions.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

-------NP Array function ----

In [32]:
r1 = ["i","am","happy"]
r2 = ["i", "like","sunlight"]
r3 = [1,2,3]


In [34]:
newdata = np.array ([r1,r2,r3])

In [37]:
newdata #matrix of strings

array([['i', 'am', 'happy'],
       ['i', 'like', 'sunlight'],
       ['1', '2', '3']], 
      dtype='<U8')

In [36]:
type(newdata)

numpy.ndarray

In [38]:
### Dictionaries

In [39]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [40]:
Games[0]

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [41]:
Games[-1]

array([75, 51, 51, 79, 77, 76, 49, 69, 54, 62])

In [42]:
Games[0,4]

73

In [43]:
dict1 = { 'key1': 'val1','key2': 'val2', 'key3': 'val3'} # key2 provides value 2

In [45]:
dict1['key2']

'val2'

In [46]:
Sdict   #seasons

{'2005': 0,
 '2006': 1,
 '2007': 2,
 '2008': 3,
 '2009': 4,
 '2010': 5,
 '2011': 6,
 '2012': 7,
 '2013': 8,
 '2014': 9}

In [47]:
Pdict # players dictionary

{'CarmeloAnthony': 3,
 'ChrisBosh': 5,
 'ChrisPaul': 6,
 'DerrickRose': 8,
 'DwayneWade': 9,
 'DwightHoward': 4,
 'JoeJohnson': 1,
 'KevinDurant': 7,
 'KobeBryant': 0,
 'LeBronJames': 2}

In [49]:
Pdict['KobeBryant']

0

In [50]:
Games[0]

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [51]:
Pdict['DerrickRose']

8

In [52]:
Games[8]

array([40, 40, 40, 81, 78, 81, 39,  0, 10, 51])

In [54]:
Games[Pdict['DerrickRose']]

array([40, 40, 40, 81, 78, 81, 39,  0, 10, 51])

In [55]:
Games[Pdict['DerrickRose']][7]  # it will tell us point scored of DerricRose in season 8

0

In [58]:
Games[Pdict['DerrickRose']][Sdict['2012']]  # it will tell us point scored of DerricRose in season 8

0

In [59]:
Points[Pdict['KobeBryant']][Sdict['2011']] # season and player dictionary , we are able to tell how much scored
# by Kobe Bryant in year 2011

1616

In [60]:
Points[Pdict['KobeBryant']]

array([2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782])

----- # Matrix Operations # ----

In [61]:
Salary

array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [62]:
# Salary[][]
print([Pdict['LeBronJames']])
print([Sdict['2009']])

[2]
[4]


In [63]:
Salary[2][4]

15779912

In [64]:
Salary[Pdict['LeBronJames']][Sdict['2009']]

15779912

In [66]:
FieldGoals

array([[978, 813, 775, 800, 716, 740, 574, 738,  31, 266],
       [632, 536, 647, 620, 635, 514, 423, 445, 462, 446],
       [875, 772, 794, 789, 768, 758, 621, 765, 767, 624],
       [756, 691, 728, 535, 688, 684, 441, 669, 743, 358],
       [468, 526, 583, 560, 510, 619, 416, 470, 473, 251],
       [549, 543, 507, 615, 600, 524, 393, 485, 492, 343],
       [407, 381, 630, 631, 314, 430, 425, 412, 406, 568],
       [306, 306, 587, 661, 794, 711, 643, 731, 849, 238],
       [208, 208, 208, 574, 672, 711, 302,   0,  58, 338],
       [699, 472, 439, 854, 719, 692, 416, 569, 415, 509]])

In [68]:
# how many goals scored by each player in each game

In [83]:
import warnings      # we used import "warnings" lib as we were dividing 0/ something which was giving an  
                     # warning for an error.
warnings.filterwarnings('ignore')

Fieldgoal_pergame = np.matrix.round(FieldGoals / Games)

In [84]:
import warnings      # we used import "warnings" lib as we were dividing 0/ something which was giving an  
                     # warning for an error.
warnings.filterwarnings('ignore')

MinutesPG = np.matrix.round(MinutesPlayed / Games)

In [85]:
MinutesPlayed

array([[3277, 3140, 3192, 2960, 2835, 2779, 2232, 3013,  177, 1207],
       [3340, 2359, 3343, 3124, 2886, 2554, 2127, 2642, 2575, 2791],
       [3361, 3190, 3027, 3054, 2966, 3063, 2326, 2877, 2902, 2493],
       [2941, 2486, 2806, 2277, 2634, 2751, 1876, 2482, 2982, 1428],
       [3021, 3023, 3088, 2821, 2843, 2935, 2070, 2722, 2396, 1223],
       [2751, 2658, 2425, 2928, 2526, 2795, 2007, 2454, 2531, 1556],
       [2808, 2353, 3006, 3002, 1712, 2880, 2181, 2335, 2171, 2857],
       [1255, 1255, 2768, 2885, 3239, 3038, 2546, 3119, 3122,  913],
       [1168, 1168, 1168, 3000, 2871, 3026, 1375,    0,  311, 1530],
       [2892, 1931, 1954, 3048, 2792, 2823, 1625, 2391, 1775, 1971]])

In [88]:
# Salary earned per game per season

import warnings      # we used import "warnings" lib as we were dividing 0/ something which was giving an  
                     # warning for an error.
warnings.filterwarnings('ignore')

Sal_pergame_per_season = np.matrix.round(Salary / Games)
print(Sal_pergame_per_season)

[[  199336.   230114.   237691.   259299.   315539.   302515.   435250.
    357040.  5075634.   671429.]
 [  146341.   223582.   164492.   180159.   197063.   226729.   300643.
    274342.   271731.   289760.]
 [   58504.    74719.   173883.   177908.   207630.   183544.   258427.
    230855.   247630.   299194.]
 [   46420.    72216.   169367.   218342.   228694.   222717.   336701.
    290299.   291006.   561450.]
 [   54795.    58619.    73918.   174152.   185397.   213425.   335033.
    257057.   288918.   522836.]
 [   47829.    61380.   185896.   187150.   225427.   188312.   281096.
    237095.   241361.   469191.]
 [   40311.    52815.    45200.    58643.   300456.   186752.   272663.
    253992.   301104.   244739.]
 [       0.        0.    52140.    60595.    58499.    77611.   234949.
    205798.   220156.   703542.]
 [       0.        0.        0.    59541.    66468.    68471.   179326.
        inf  1763269.   369860.]
 [   40426.    75322.   255711.   182412.   204934.   1

In [89]:
# Salary paid for each goal in a season
import warnings      # we used import "warnings" lib as we were dividing 0/ something which was giving an  
                     # warning for an error.
warnings.filterwarnings('ignore')

Sal_pergoal = np.matrix.round(Salary / FieldGoals)
print(Sal_pergoal)

[[  16306.   21794.   25149.   26578.   32171.   33522.   43980.   37736.
   982381.   88346.]
 [  18987.   23776.   20848.   22956.   23585.   31760.   42644.   44388.
    46465.   51975.]
 [   5282.    7549.   16425.   18264.   20547.   19129.   25801.   22935.
    24860.   33084.]
 [   4912.    6793.   17914.   26936.   22936.   25072.   41992.   29073.
    30158.   62732.]
 [   9601.    9138.   10397.   24568.   29809.   26894.   43490.   41567.
    43368.   85403.]
 [   6098.    7800.   24566.   23432.   26300.   27672.   40770.   36175.
    38755.   60188.]
 [   7725.    8872.    5740.    7249.   43059.   34745.   38494.   43154.
    45981.   35332.]
 [      0.       0.    7106.    6784.    6041.    8514.   24116.   22804.
    21004.   79814.]
 [      0.       0.       0.    8402.    7715.    7801.   23158.      inf
   304012.   55807.]
 [   4338.    8139.   29707.   16874.   21947.   20520.   37719.   30197.
    44995.   29470.]]


In [95]:
Sal_pergoal.max(1)

array([ 982381.,   51975.,   33084.,   62732.,   85403.,   60188.,
         45981.,   79814.,      inf,   44995.])

In [97]:
# in how many attempts goal was scored?
import warnings      # we used import "warnings" lib as we were dividing 0/ something which was giving an  
                     # warning for an error.
warnings.filterwarnings('ignore')

FG_perattempt = np.matrix.round(FieldGoalAttempts / FieldGoals)
print(FG_perattempt)

[[  2.   2.   2.   2.   2.   2.   2.   2.   2.   3.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]
 [  2.   2.   2.   2.   2.   2.   2.  nan   3.   2.]
 [  2.   2.   2.   2.   2.   2.   2.   2.   2.   2.]]
